<?php

require_once ("templates/header.phtml");

?>

<div class="column is-narrow">
    <div class="title has-text-centered">My Profile</div>

    <?php
    // Show success message if applicable
    if (isset($view->message)) {
        echo '<div class="columns is-centered"><div class="column is-narrow">';
        echo '<div class="notification is-success">'.$view->message.'</div>';
        echo '</div></div>';
    }

    // load modals
    require_once("Views/templates/modal/changeProfile.phtml");
    require_once("Views/templates/modal/changePassword.phtml");
    require_once("Views/templates/modal/changeImage.phtml");

    ?>
    <div></div>
    <div class="columns is-centered">
        <figure class="image is-96x96">
            <img src="<?php echo $view->user->getImage(); ?>" class="is-rounded">
        </figure>
    </div>
    <button class="button is-info is-medium is-fullwidth js-modal-trigger" data-target="js-modal-image">Upload New Image</button>
    <?php

    if ($view->user->getImage() != 'images/profile/0.png') {
        echo '<a href="profile.php?action=removeImage" class="button is-danger is-medium is-fullwidth">Remove Image</a>';
    }

    ?>
    <table class="table is-striped is-hoverable subtitle">
        <tbody>
            <tr>
                <td>Username:</td>
                <td><?php echo $view->user->getUsername(); ?></td>
            </tr>
            <tr>
                <td>First Name:</td>
                <td><?php echo $view->user->getFirstName(); ?></td>
            </tr>
            <tr>
                <td>Last Name:</td>
                <td><?php echo $view->user->getLastName(); ?></td>
            </tr>
            <tr>
                <td>Email Address:</td>
                <td><?php echo $view->user->getEmail(); ?></td>
            </tr>
        </tbody>
    </table>
    <button class="button is-info is-fullwidth is-medium js-modal-trigger" data-target="js-modal-profile">Edit Details</button>
    <br />
    <button class="button is-warning is-fullwidth is-medium js-modal-trigger" data-target="js-modal-password">Change Password</button>

</div>

<script src="js/modal.js"></script>
<?php

require_once ("templates/footer.phtml");

?>

