<div class="title">
    Login
</div>
<div>
    <a href="login.php">New? Sign up here</a>
</div>

<form class="login" method="post" action="login.php">
    <div class="field">
        <label class="label">Email</label>
        <div class="control">
            <input name="email" class="input" type="email" placeholder="Email">
        </div>
    </div>

    <div class="field">
        <label class="label">Password</label>
        <div class="control">
            <input name="password" class="input" type="password" placeholder="Password">
        </div>
    </div>
    <button name="login" class="button is-success">Login</button>
</form>