<div id="js-modal-image" class="modal">
    <div class="modal-background"></div>
    <div class="modal-card">
        <header class="modal-card-head">
            <p class="modal-card-title">Upload a picture</p>
            <button class="delete" aria-label="close"></button>
        </header>
        <form method="POST" action="profile.php">
            <section class="modal-card-body">
                <div class="subtitle columns is-centered">Only PNG images are accepted</div>
                <div class="columns is-centered file is-large is-boxed">
                    <label class="file-label">
                        <input name="file" accept="image/png" class="file-input" type="file" required>
                        <span class="file-cta">
                            Select file…
                        </span>
                    </label>
                </div>
            </section>
            <footer class="modal-card-foot">
                <button name="image" class="button is-success">Changes image</button>
                <button onclick="return false" class="button close">Cancel</button>
            </footer>
        </form>
    </div>
</div>